SERVER_PORT: 22003
EUREKA_HOST_1: 10.1.7.186
EUREKA_PORT_1: 22001
EUREKA_HOST_2: 10.1.7.187
EUREKA_PORT_2: 22002

spring:
  application:
    name: hotel-eureka
eureka:
  environment: prod
  server:
    enable-self-preservation: false
  instance:
      hostname: localhost
      status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
       defaultZone: http://${EUREKA_HOST_2:localhost}:${EUREKA_PORT_2:22002}/eureka/,http://${EUREKA_HOST_1:localhost}:${EUREKA_PORT_1:22001}/eureka/
server:
  port: ${SERVER_PORT:22003}

logging:
  file: /var/log/hotel-eureka/inf-eureka.log