# 注册和发现
#server:
#  port: 8763
#spring:
#  application:
#    name: consul-provider
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        serviceName: consul-provider
spring:
  profiles:
    active: dev
